# Generated by Django 5.0.3 on 2024-07-06 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catatan',
            old_name='isi',
            new_name='konten',
        ),
        migrations.RenameField(
            model_name='komentar',
            old_name='teks',
            new_name='konten',
        ),
        migrations.RemoveField(
            model_name='catatan',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='dibuat_pada',
        ),
        migrations.AddField(
            model_name='catatan',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='komentar',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='komentar',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='komentar',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='notes.kategori'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='catatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='notes.catatan'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
