# Generated by Django 5.0.3 on 2024-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_isi_catatan_konten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatan',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
