# Generated by Django 5.0.3 on 2024-07-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_catatan_tanggal_dibuat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catatan',
            old_name='konten',
            new_name='isi',
        ),
        migrations.RenameField(
            model_name='komentar',
            old_name='tanggal_dibuat',
            new_name='dibuat_pada',
        ),
        migrations.RenameField(
            model_name='komentar',
            old_name='konten',
            new_name='teks',
        ),
        migrations.RemoveField(
            model_name='catatan',
            name='tanggal_dibuat',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='nama',
        ),
        migrations.AddField(
            model_name='catatan',
            name='tags',
            field=models.ManyToManyField(to='notes.tag'),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='judul',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.kategori'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='catatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.catatan'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
